<?php

namespace Salonlar\SalonBundle\Repository;
use Salonlar\SalonBundle\Entity\customer;

/**
 * Salon1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customerRepository extends \Doctrine\ORM\EntityRepository
{
    public function newPerson($name="",$email="",$phone="")
    {
        $salon = new customer();
        $salon->setName($name)
            ->setEmail($email)
            ->setPhone($phone)
        ;
        return $salon;
    }
}
