<?php

namespace Salonlar\SalonBundle\Repository;
use Salonlar\SalonBundle\Entity\Salon1;

/**
 * Salon1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Salon1Repository extends \Doctrine\ORM\EntityRepository
{
    public function newSalon1($title="",$content="")
    {
        $salon = new Salon1();
        $salon->setTitle($title)
            ->setContent($content);
        return $salon;
    }
}
