<?php

namespace Salonlar\SalonBundle\Repository;

/**
 * Salon1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Salon1Repository extends \Doctrine\ORM\EntityRepository
{
}
