<?php

namespace Salonlar\SalonBundle\Repository;

/**
 * sinasi_ARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sinasi_ARepository extends \Doctrine\ORM\EntityRepository
{
}
