<?php

namespace Salonlar\SalonBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class customerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class,[
                'label' => ' ',
                'attr'=> [
                    'class' => 'form-control',
                    'placeholder' => 'İsim-Soyad'
                ],
            ])
            ->add('email',TextType::class,[
                'label' => ' ',
                'attr'=> [
                    'type' => 'email',
                    'class' => 'form-control',
                    'placeholder' => 'Emial'
                ]
            ])
            ->add('phone',TextType::class,[
                'label' => ' ',
                'attr'=> [
                    'type' => 'number',
                    'class' => 'form-control',
                    'placeholder' => 'Telefon'
                ]
            ])
            ->add('submit',SubmitType::class,[
                'label'=>'Gönder'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
           'data_class'=>'Salonlar\SalonBundle\Entity\customer',
            'action' => 'listing'
        ]);
    }

    public function getBlockPrefix()
    {
        return null; // TODO: Change the autogenerated stub
    }
}
