<?php

namespace Salonlar\SalonBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class sinasiType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('a1', CheckboxType::class,[
                'required' => false,
                'data' => true,
                'attr' => [
                    'name' => 'a1',
                    'id' => 'a1',
                    'for' => 'a1',
                    'value' => '1'
                ],
                'label' => ' ',
                'label_attr' => [
                    'for' => 'a1'
                ],
            ])
            ->add('a2', CheckboxType::class,[

                'required' => false,
                'label' => ' ',
                'data' => true,
                'label_attr' => [
                    'for' => 'a2'
                ],
                'attr' => [
                    'name' => 'a2',
                    'id' => 'a2',
                    'for' => 'a2',
                    'value' => '1'
                ],
            ])
            ->add('a3', CheckboxType::class,[
                'label' => ' ',
                'data' => true,
                'label_attr' => [
                    'for' => 'a3'
                ],
                'attr' => [
                    'name' => 'a3',
                    'id' => 'a3',
                    'for' => 'a3',
                    'value' => '1'
                ],
            ])
            ->add('a4', CheckboxType::class,[
                'label' => ' ',
                'data' => true,
                'label_attr' => [
                    'for' => 'a1'
                ],
                'attr' => [
                    'name' => 'a4',
                    'id' => 'a4',
                    'for' => 'a4',
                    'value' => '1'
                ],
            ])
            ->add('a5', CheckboxType::class,[
                'label' => ' ',
                'data' => true,
                'label_attr' => [
                    'for' => 'a1'
                ],
                'attr' => [
                    'name' => 'a5',
                    'id' => 'a5',
                    'for' => 'a5',
                    'value' => '1'
                ],
            ])
            ->add('a6')
            ->add('a7')
            ->add('a8')
            ->add('a9')
            ->add('a10')
            ->add('a11')
            ->add('a12')
            ->add('a13')
            ->add('a14')
            ->add('a15')
            ->add('a17')
            ->add('a16')
            ->add('a18')
            ->add('a19')
            ->add('a20')
            ->add('a21')
            ->add('b1')
            ->add('b2')
            ->add('b3')
            ->add('b4')
            ->add('b5')
            ->add('b6')
            ->add('b7')
            ->add('b8')
            ->add('b9')
            ->add('b10')
            ->add('b11')
            ->add('b12')
            ->add('b13')
            ->add('b14')
            ->add('b15')
            ->add('b16')
            ->add('b17')
            ->add('b18')
            ->add('b19')
            ->add('b20')
            ->add('b21')
            ->add('b22')
            ->add('b23')
            ->add('c1')
            ->add('c2')
            ->add('c4')
            ->add('c3')
            ->add('c5')
            ->add('c6')
            ->add('c7')
            ->add('c8')
            ->add('c9')
            ->add('c10')
            ->add('c11')
            ->add('c12')
            ->add('c13')
            ->add('c14')
            ->add('c15')
            ->add('c16')
            ->add('c17')
            ->add('c18')
            ->add('c19')
            ->add('c20')
            ->add('c21')
            ->add('c22')
            ->add('c23')
            ->add('c24')
            ->add('c25')
            ->add('d1')
            ->add('d2')
            ->add('d3')
            ->add('d4')
            ->add('d5')
            ->add('d6')
            ->add('d7')
            ->add('d8')
            ->add('d9')
            ->add('d10')
            ->add('d11')
            ->add('d12')
            ->add('d13')
            ->add('d14')
            ->add('d15')
            ->add('d16')
            ->add('d17')
            ->add('d18')
            ->add('d19')
            ->add('d20')
            ->add('d21')
            ->add('d22')
            ->add('d23')
            ->add('d24')
            ->add('d25')
            ->add('d26')
            ->add('d27')
            ->add('e1')
            ->add('e2')
            ->add('e3')
            ->add('e4')
            ->add('e5')
            ->add('e6')
            ->add('e7')
            ->add('e8')
            ->add('e9')
            ->add('e10')
            ->add('e11')
            ->add('e12')
            ->add('e13')
            ->add('e14')
            ->add('e15')
            ->add('e16')
            ->add('e17')
            ->add('e18')
            ->add('e19')
            ->add('e20')
            ->add('e21')
            ->add('e22')
            ->add('e23')
            ->add('e24')
            ->add('e25')
            ->add('e26')
            ->add('e27')
            ->add('e28')
            ->add('e29')
            ->add('f1')
            ->add('f2')
            ->add('f3')
            ->add('f4')
            ->add('f5')
            ->add('f6')
            ->add('f7')
            ->add('f8')
            ->add('f9')
            ->add('f10')
            ->add('f11')
            ->add('f12')
            ->add('f13')
            ->add('f14')
            ->add('f15')
            ->add('f16')
            ->add('f17')
            ->add('f18')
            ->add('f19')
            ->add('f20')
            ->add('f21')
            ->add('f22')
            ->add('f23')
            ->add('f24')
            ->add('f25')
            ->add('f26')
            ->add('f27')
            ->add('f28')
            ->add('f29')
            ->add('g1')
            ->add('g2')
            ->add('g3')
            ->add('g4')
            ->add('g5')
            ->add('g6')
            ->add('g7')
            ->add('g8')
            ->add('g9')
            ->add('g10')
            ->add('g11')
            ->add('g12')
            ->add('g13')
            ->add('g14')
            ->add('g15')
            ->add('g16')
            ->add('g17')
            ->add('g18')
            ->add('g19')
            ->add('g20')
            ->add('g21')
            ->add('g22')
            ->add('g23')
            ->add('g24')
            ->add('g25')
            ->add('g26')
            ->add('g27')
            ->add('h1')
            ->add('h2')
            ->add('h3')
            ->add('h4')
            ->add('h5')
            ->add('h6')
            ->add('h7')
            ->add('h8')
            ->add('h9')
            ->add('h10')
            ->add('h11')
            ->add('h12')
            ->add('h13')
            ->add('h14')
            ->add('h15')
            ->add('h16')
            ->add('h17')
            ->add('h18')
            ->add('h19')
            ->add('h20')
            ->add('h21')
            ->add('h22')
            ->add('h23')
            ->add('h24')
            ->add('h25')
            ->add('h26')
            ->add('h27')
            ->add('i1')
            ->add('i2')
            ->add('i3')
            ->add('i4')
            ->add('i5')
            ->add('i6')
            ->add('i7')
            ->add('i8')
            ->add('i9')
            ->add('i10')
            ->add('i11')
            ->add('i12')
            ->add('i13')
            ->add('i14')
            ->add('i15')
            ->add('i16')
            ->add('i17')
            ->add('i18')
            ->add('i19')
            ->add('i20')
            ->add('i21')
            ->add('i22')
            ->add('i23')
            ->add('i24')
            ->add('i25')
            ->add('i26')
            ->add('i27')
            ->add('i28')
            ->add('i29')
            ->add('j1')
            ->add('j2')
            ->add('j3')
            ->add('j4')
            ->add('j5')
            ->add('j6')
            ->add('j7')
            ->add('j8')
            ->add('j9')
            ->add('j10')
            ->add('j11')
            ->add('j12')
            ->add('j13')
            ->add('j14')
            ->add('j15')
            ->add('j16')
            ->add('j17')
            ->add('j18')
            ->add('j19')
            ->add('j20')
            ->add('j21')
            ->add('j22')
            ->add('j23')
            ->add('j24')
            ->add('j25')
            ->add('j26')
            ->add('j27')
            ->add('j28')
            ->add('j29')
            ->add('j30')
            ->add('j31')
            ->add('k1')
            ->add('k2')
            ->add('k3')
            ->add('k4')
            ->add('k5')
            ->add('k6')
            ->add('k7')
            ->add('k8')
            ->add('k9')
            ->add('k10')
            ->add('k11')
            ->add('k12')
            ->add('k13')
            ->add('k14')
            ->add('k15')
            ->add('k16')
            ->add('k17')
            ->add('k18')
            ->add('k19')
            ->add('k20')
            ->add('k21')
            ->add('k22')
            ->add('k23')
            ->add('k24')
            ->add('k25')
            ->add('k26')
            ->add('k27')
            ->add('k28')
            ->add('k29')
            ->add('l1')
            ->add('l2')
            ->add('l3')
            ->add('l4')
            ->add('l5')
            ->add('l6')
            ->add('l7')
            ->add('l8')
            ->add('l9')
            ->add('l10')
            ->add('l11')
            ->add('l12')
            ->add('l13')
            ->add('l14')
            ->add('l15')
            ->add('l16')
            ->add('l17')
            ->add('l18')
            ->add('l19')
            ->add('l20')
            ->add('l21')
            ->add('l22')
            ->add('l23')
            ->add('l25')
            ->add('l26')
            ->add('l27')
            ->add('l28')
            ->add('l29')
            ->add('l30')
            ->add('l31')
            ->add('m1')
            ->add('m2')
            ->add('m3')
            ->add('m4')
            ->add('m5')
            ->add('m6')
            ->add('m7')
            ->add('m8')
            ->add('m9')
            ->add('m10')
            ->add('m11')
            ->add('m12')
            ->add('m13')
            ->add('m14')
            ->add('m15')
            ->add('m16')
            ->add('m17')
            ->add('m18')
            ->add('m19')
            ->add('m20')
            ->add('m21')
            ->add('m22')
            ->add('m23')
            ->add('m24')
            ->add('m25')
            ->add('m26')
            ->add('m27')
            ->add('m28')
            ->add('m29')
            ->add('n1')
            ->add('n2')
            ->add('n3')
            ->add('n4')
            ->add('n5')
            ->add('n6')
            ->add('n7')
            ->add('n8')
            ->add('n9')
            ->add('n10')
            ->add('n11')
            ->add('n12')
            ->add('n13')
            ->add('n14')
            ->add('n15')
            ->add('n16')
            ->add('n17')
            ->add('n18')
            ->add('n19')
            ->add('n20')
            ->add('n21')
            ->add('n22')
            ->add('n23')
            ->add('n24')
            ->add('n25')
            ->add('n26')
            ->add('n27')
            ->add('o1')
            ->add('o2')
            ->add('o3')
            ->add('o4')
            ->add('o5')
            ->add('o6')
            ->add('o7')
            ->add('o8')
            ->add('o9')
            ->add('o10')
            ->add('o11')
            ->add('o12')
            ->add('o13')
            ->add('o14')
            ->add('o15')
            ->add('o16')
            ->add('o17')
            ->add('o18')
            ->add('o19')
            ->add('o20')
            ->add('o21')
            ->add('o22')
            ->add('o23')
            ->add('o24')
            ->add('o25')
            ->add('p1')
            ->add('p2')
            ->add('p3')
            ->add('p4')
            ->add('p5')
            ->add('p6')
            ->add('p7')
            ->add('p8')
            ->add('p9')
            ->add('p10')
            ->add('p11')
            ->add('p12')
            ->add('p13')
            ->add('p14')
            ->add('p15')
            ->add('p16')
            ->add('p17')
            ->add('p18')
            ->add('p19')
            ->add('p20')
            ->add('p21')
            ->add('p22')
            ->add('p23')
            ->add('p24')
            ->add('p25')
            ->add('r1')
            ->add('r2')
            ->add('r3')
            ->add('r4')
            ->add('r5')
            ->add('r6')
            ->add('r7')
            ->add('r8')
            ->add('r9')
            ->add('r10')
            ->add('r11')
            ->add('r12')
            ->add('r13')
            ->add('r14')
            ->add('r15')
            ->add('r16')
            ->add('r17')
            ->add('r18')
            ->add('r19')
            ->add('r20')
            ->add('r21')
            ->add('r22')
            ->add('r23')
            ->add('r24')
            ->add('r25')
            ->add('s1')
            ->add('s2')
            ->add('s3')
            ->add('s4')
            ->add('s5')
            ->add('s6')
            ->add('s7')
            ->add('s8')
            ->add('s9')
            ->add('s10')
            ->add('s11')
            ->add('s12')
            ->add('s13')
            ->add('s14')
            ->add('s15')
            ->add('s16')
            ->add('s17')
            ->add('s18')
            ->add('s19')
            ->add('s20')
            ->add('s21')
            ->add('s22')
            ->add('s23')
            ->add('t1')
            ->add('t2')
            ->add('t3')
            ->add('t4')
            ->add('t5')
            ->add('t6')
            ->add('t7')
            ->add('t8')
            ->add('t9')
            ->add('t10')
            ->add('t11')
            ->add('t12')
            ->add('t13')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Salonlar\SalonBundle\Entity\sinasi'
        ));
    }

    public function getBlockPrefix()
    {
        return null; // TODO: Change the autogenerated stub
    }
}
